# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Nathan\Documents\ECAM5\PAM\StackedWidget\V2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 460))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Machine1 = QtWidgets.QWidget()
        self.Machine1.setObjectName("Machine1")
        self.label = QtWidgets.QLabel(self.Machine1)
        self.label.setGeometry(QtCore.QRect(350, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.Machine1)
        self.tableWidget.setGeometry(QtCore.QRect(100, 70, 600, 350))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.stackedWidget.addWidget(self.Machine1)
        self.Machine2 = QtWidgets.QWidget()
        self.Machine2.setObjectName("Machine2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.Machine2)
        self.tableWidget_3.setGeometry(QtCore.QRect(100, 70, 600, 350))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(self.Machine2)
        self.label_4.setGeometry(QtCore.QRect(350, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.Machine2)
        self.Machine3 = QtWidgets.QWidget()
        self.Machine3.setStyleSheet("")
        self.Machine3.setObjectName("Machine3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.Machine3)
        self.tableWidget_2.setGeometry(QtCore.QRect(100, 70, 600, 350))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_5 = QtWidgets.QLabel(self.Machine3)
        self.label_5.setGeometry(QtCore.QRect(350, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.Machine3)
        self.Machine4 = QtWidgets.QWidget()
        self.Machine4.setObjectName("Machine4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.Machine4)
        self.tableWidget_4.setGeometry(QtCore.QRect(100, 70, 600, 350))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.label_6 = QtWidgets.QLabel(self.Machine4)
        self.label_6.setGeometry(QtCore.QRect(350, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.Machine4)
        self.Machine1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Machine1_2.setGeometry(QtCore.QRect(60, 500, 75, 23))
        self.Machine1_2.setObjectName("Machine1_2")
        self.Machine2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Machine2_2.setGeometry(QtCore.QRect(240, 500, 75, 23))
        self.Machine2_2.setObjectName("Machine2_2")
        self.Machine3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Machine3_2.setGeometry(QtCore.QRect(420, 500, 75, 23))
        self.Machine3_2.setObjectName("Machine3_2")
        self.Close = QtWidgets.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(690, 530, 75, 23))
        self.Close.setObjectName("Close")
        self.Machine3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Machine3_3.setGeometry(QtCore.QRect(600, 500, 75, 23))
        self.Machine3_3.setObjectName("Machine3_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Machine 1"))
        self.label_4.setText(_translate("MainWindow", "Machine 2"))
        self.label_5.setText(_translate("MainWindow", "Machine 3"))
        self.label_6.setText(_translate("MainWindow", "Machine 4"))
        self.Machine1_2.setText(_translate("MainWindow", "Machine 1"))
        self.Machine2_2.setText(_translate("MainWindow", "Machine 2"))
        self.Machine3_2.setText(_translate("MainWindow", "Machine 3"))
        self.Close.setText(_translate("MainWindow", "Close"))
        self.Machine3_3.setText(_translate("MainWindow", "Machine 4"))

